[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.ci]
via_ir = true

[rpc_endpoints]
ink = "https://rpc-gel.inkonchain.com"
ethereum = "${ETH_RPC_URL}"

[etherscan]
ink = { key = "verifyContract", chain = 57073, url = "https://explorer.inkonchain.com/api/" }
ethereum = { key = "${ETHERSCAN_API_KEY}", chain = 1 }
